### ISSUE TITLE
Provide a way to customise the ScrollPane used by the RouteNode

### ISSUE THREAD

**Issue by dlemmermann** [dlemmermann/jfxcentral2#239]
It should be possible for the app developer to replace / customise the ScrollPane that is used for scrolling the content.

**Comment by FlorianKirmaier** [comment]
It can now be set with the system property `-Drouting.scrollpane=<your-classname>`

**Comment by dlemmermann** [comment]
Can't we do this in code? Why not override the method in RoutePane that creates the scroll pane?
