### ISSUE TITLE
LOTW submenu is not OK

### ISSUE THREAD

**Issue by FDelporte** [dlemmermann/jfxcentral2#272]
Paging at the bottom works OK, but the submenu/tabs are showing strange dates

![Screenshot 2023-06-16 at 14 53 52](https://github.com/dlemmermann/jfxcentral2/assets/1415873/4ab47285-cd82-40ab-a1f3-eff19ab112aa)

**Comment by FDelporte** [comment]
@dlemmermann probably related to ID changes, please assign to me

**Comment by dlemmermann** [comment]
I do not think this is related to your changes. This is simply us using the wrong order of the list.

**Comment by dlemmermann** [comment]
Look for LinksOfTheWeekPage.

**Comment by FDelporte** [comment]
Issue no longer valid, works OK with latest code
