### ISSUE TITLE
Resizing the application window is quite laggy

### ISSUE THREAD

**Issue by crschnick** [dlemmermann/jfxcentral2#285]
When resizing the window and the layout changes between the wide and more condensed layouts, the window lags and flickers quite a bit.

**Comment by dlemmermann** [comment]
In desktop or browser mode?

**Comment by crschnick** [comment]
In desktop mode on Windows I get some flickering, but that seems more like a problem that Windows has with slowly responding application windows when resizing.

**Comment by crschnick** [comment]
Maybe this is accentuated by using a potato PC, but in general the resizing causes weird behavior for me:

https://github.com/dlemmermann/jfxcentral2/assets/72509152/3a70bb31-fc2b-4555-992b-3deb069370c8

**Comment by dlemmermann** [comment]
What exactly is "weird"? Can you please be more specific in your tickets? In the video I can see that the window first jumps to the upper left corner and then gets bigger. This is almost like a slow-motion video capture of the resizing behaviour. None of us have observed this. I am not sure what exactly defines a "potato" PC but this seems to be a pretty slow machine. Or is it maybe a machine without a GPU?

**Comment by dlemmermann** [comment]
I think it is OK to close this ticket, assuming that it is a hardware issue .... as in "slow" hardware :-)
