### ISSUE TITLE
Fullscreen mode window still has a border

### ISSUE THREAD

**Issue by crschnick** [dlemmermann/jfxcentral2#287]

**Comment by dlemmermann** [comment]
Please include a screenshot. Currently we do not support "fullscreen", only "max" screen. On Mac that means it is not covering the menubar at the top or the dock at the bottom. So it really still is a window and the user can directly resize it going from there. But I guess it is different on Windows?

**Comment by crschnick** [comment]
I am talking about the white border here:
![image](https://github.com/dlemmermann/jfxcentral2/assets/72509152/e0b0071e-5da3-468b-b1fc-73ebea2fe718)

If that is intended, then I guess this can be closed. I just assumed by how the button looked like that this was intended to be fullscreen, not max screen.

**Comment by dlemmermann** [comment]
"white" border? I only see a dark blue border around the whole window ... which is by design.

**Comment by crschnick** [comment]
Is your GitHub set to light mode? In dark mode it should be visible

**Comment by dlemmermann** [comment]
Thanks for the tip .... yes, now I can see it, too. I have not observed this on Mac. Is the white border showing only when in full / max mode?

**Comment by crschnick** [comment]
Now that I have played around with it, it is only visible when the window has focus and is caused by this rule: https://github.com/dlemmermann/jfxcentral2/blob/755a9050f28769a43c25390d3a8198f55a3795ee/app/src/main/resources/com/dlsc/jfxcentral2/app/stage/stage.css#L10-L13 . What is the purpose of that rule?

**Comment by dlemmermann** [comment]
Nice catch. Yes, this is a "feature", not a bug. But a feature needed by another app I worked on. I will remove it.

**Comment by dlemmermann** [comment]
Fix pushed.

**Comment by dlemmermann** [comment]
I have changed the maximize behavior to use the full-screen mode. Please verify on your system if this works now as expected.

**Comment by crschnick** [comment]
Yes that looks good now
