### ISSUE TITLE
SearchFilterView needs to update its predicate in a delayed way

### ISSUE THREAD

**Issue by dlemmermann** [dlemmermann/jfxcentral2#289]
When entering a search / filter text that updates a grid view one can tell that it is slow. I think this is because the predicate gets updated IMMEDIATELY after each key pressed event. This then recreates the grid view. We should use the javafx.concurrent API and a service to delay the update by 200 milliseconds. Use Service.restart() to rerun the service and its task whenever a key gets  pressed. Restarting a service cancels the task it is using. Let me know if the pattern is not clear.

The following code shows the concepts (taken from SearchField in GemsFX):

```java
    private class SearchService extends Service<Collection<T>> {

        private String text;

        @Override
        protected Task<Collection<T>> createTask() {
            text = editor.getText();
            return new SearchTask(text);
        }

        public String getText() {
            return text;
        }
    }

    private class SearchTask extends Task<Collection<T>> {

        private final String searchText;

        public SearchTask(String searchText) {
            this.searchText = searchText;
        }

        @Override
        protected Collection<T> call() throws Exception {
            Thread.sleep(250);

            if (!isCancelled() && StringUtils.isNotBlank(searchText)) {
                return getSuggestionProvider().call(new SearchFieldSuggestionRequest() {
                    @Override
                    public boolean isCancelled() {
                        return SearchTask.this.isCancelled();
                    }

                    @Override
                    public String getUserText() {
                        return searchText;
                    }
                });
            }

            return Collections.emptyList();
        }
    }
```
You can still use your current binding code in SearchFilterView. Just bind it to an intermediate text property which gets updated by the service based on the text property of the SearchField.

**We do not need this delayed update for the other filters / the dropdowns. We only need it for the text field.**

**Comment by leewyatt** [comment]
Thank you, you always describe issues very clearly and even provide solutions. 
I have learned a lot from you.
