### ISSUE TITLE
VideoTileView is too wide in large.

### ISSUE THREAD

**Issue by dlemmermann** [dlemmermann/jfxcentral2#299]
<img width="1614" alt="Bildschirmfoto 2023-06-21 um 20 29 44" src="https://github.com/dlemmermann/jfxcentral2/assets/9534301/5c4496fd-a3b9-4a2c-87e1-fa3caccdfe8d">

**Comment by dlemmermann** [comment]
@leewyatt this is fixed, right?

**Comment by leewyatt** [comment]
> @leewyatt this is fixed, right?

Yes, it is fixed in larger sizes, but we can limit the maximum width.
