### ISSUE TITLE
Add Mastodon icon to font set

### ISSUE THREAD

**Issue by FDelporte** [dlemmermann/jfxcentral2#310]
https://github.com/dlemmermann/jfxcentral2/blob/develop/iconfont/src/main/resources/com/dlsc/jfxcentral2/iconfont/jfxcentral2-icons.ttf

The logo is available here
https://joinmastodon.org/branding

**Comment by dlemmermann** [comment]
@leewyatt maybe check first if any of the icon fonts already contains it.

**Comment by leewyatt** [comment]
> @leewyatt maybe check first if any of the icon fonts already contains it.
The icon already exists in the CoreUiBrands font.
![image](https://github.com/dlemmermann/jfxcentral2/assets/75261429/4261e7cf-b74e-485f-a6be-71d3108f9692)

**Comment by FDelporte** [comment]
Thanks for finding out @leewyatt !
