### ISSUE TITLE
LOTW on start page too big when shown on small devices

### ISSUE THREAD

**Issue by dlemmermann** [dlemmermann/jfxcentral2#313]
The screenshot shows how the LOTW section on the start page is being cut off when the app is displayed on a phone.

<img width="709" alt="Bildschirmfoto 2023-06-26 um 14 02 10" src="https://github.com/dlemmermann/jfxcentral2/assets/9534301/c0dc4a19-536e-4cc9-82ff-36465c212c8f">

**Comment by leewyatt** [comment]
It seems to be running fine on the current computer. I will test it again on macOS later to confirm.
![image](https://github.com/dlemmermann/jfxcentral2/assets/75261429/a96c1219-e3d0-439f-bdc8-4e4e4eac1178)

**Comment by leewyatt** [comment]
I have observed this bug on macOS Chrome and Safari as well.
