### ISSUE TITLE
The video tiles in the VideoGalleryView are not aligned with title and play area

### ISSUE THREAD

**Issue by dlemmermann** [dlemmermann/jfxcentral2#332]
<img width="1191" alt="Bildschirmfoto 2023-06-28 um 16 43 22" src="https://github.com/dlemmermann/jfxcentral2/assets/9534301/a9a6e291-a4f7-47c9-add6-502a3b7b569e">

**Comment by leewyatt** [comment]
I believe the layout in the medium size also needs to be adjusted.
![image](https://github.com/dlemmermann/jfxcentral2/assets/75261429/1167f43f-1234-49cb-aaee-636764e99f71)
