### ISSUE TITLE
Should overview pages for libraries have a preview image?

### ISSUE THREAD

**Issue by FDelporte** [dlemmermann/jfxcentral2#340]
To make these overview pages more "appealing", similar to e.g. books.

Maybe the model for these objects will need an extra field for this?

**Comment by dlemmermann** [comment]
Feel free to create a preview image for each library. Then we can modify the tile views.

**Comment by dlemmermann** [comment]
It's quite a bit of work just so you know.

**Comment by dlemmermann** [comment]
I do not want preview images for tools or blogs. It is not worth it and doesn't express much, especially since tools for example sometimes do not even have a strong visual appearance. E.g. junit or maven plugins.

**Comment by dlemmermann** [comment]
Let's not do this for now. There are plenty of other things to focus on.
