### ISSUE TITLE
Link problems for book that is not available on Amazon and/or has no ISBN

### ISSUE THREAD

**Issue by FDelporte** [dlemmermann/jfxcentral2#341]
E.g. mine "Getting started with Java on the Raspberry Pi"

Problems:
* Header shows Amazon button, but is a dead link
* Link to leanpub site (defined in url) is not shown
* Title ISBN should not be shown, if isbn is empty

**Comment by leewyatt** [comment]
![image](https://github.com/dlemmermann/jfxcentral2/assets/75261429/b1de3bfa-5080-4610-9b0d-dc049ecc8cd3)
![image](https://github.com/dlemmermann/jfxcentral2/assets/75261429/1860c4d9-d5d1-44f5-bb45-7a875c513f91)
![image](https://github.com/dlemmermann/jfxcentral2/assets/75261429/1a98016c-4a81-42cc-8be8-cf17dd11c8c7)

**Comment by FDelporte** [comment]
Thanks @leewyatt, does the model need to be extended with an extra value for the leanpub-url?

**Comment by leewyatt** [comment]
`        if (StringUtils.isNotBlank(book.getAmazonASIN())) {
            setWebsiteButtonText("amazon");
            setWebsite("https://www.amazon.com/dp/" + getModel().getAmazonASIN());
        } else if (StringUtils.isNotBlank(book.getUrl())) {
            setWebsiteButtonText(StringUtil.getDomainName(book.getUrl()));// leanpub and so on
            setWebsite(book.getUrl());
        }`
@FDelporte  I am currently using code to retrieve the domain name, and for now, I don't need to expand the model. What do you think?

**Comment by FDelporte** [comment]
Nice solution, I love it!!

**Comment by leewyatt** [comment]
Thank you~
