### ISSUE TITLE
The data is not being displayed on the OpenJFX web page.

### ISSUE THREAD

**Issue by leewyatt** [dlemmermann/jfxcentral2#372]
Even though the data is being retrieved, it is not being displayed on the web page.

![image](https://github.com/dlemmermann/jfxcentral2/assets/75261429/b2c70635-e1c0-4621-9c72-71f0f1fdd771)

**Comment by dlemmermann** [comment]
Can be related to querying too often. Works for me now. Ignore this issue for the time being.
