### ISSUE TITLE
Homepage shows oldest LOTW after navigating to LOTW page and returning

### ISSUE THREAD

**Issue by dlemmermann** [dlemmermann/jfxcentral2#384]
When pressing the "VIEW ALL LINKS OF THE WEEK" button on the homepage we get to see the dedicated LOTW page. When returning back to the homepage we suddenly see the oldest LOTW entry. At least I did, maybe it was just random. Maybe this is some side effect of shuffling / sorting the LOTW list of the DataRepository. Maybe this was introduced when linking the menu on the LOTW page to the pagination control.

<img width="1182" alt="Bildschirmfoto 2023-07-12 um 18 54 56" src="https://github.com/dlemmermann/jfxcentral2/assets/9534301/30d5baf6-bcc7-4be0-93c5-7c7a82647a6d">

**Comment by leewyatt** [comment]
You're right, it is indeed caused by the reverse operation on the LOTW list. Now I've made a copy of the LOTW list and am performing stream operations on the copy
