### ISSUE TITLE
Header Alignment Issue with Long Titles on Detail Page

### ISSUE THREAD

**Issue by leewyatt** [dlemmermann/jfxcentral2#395]
On the details page, when the header title is long, the share button located below it gets squeezed and pushed down below the content
![bug1](https://github.com/dlemmermann/jfxcentral2/assets/75261429/b01cd35a-a155-4aac-8b6b-5b4705e7e599)
![bug2](https://github.com/dlemmermann/jfxcentral2/assets/75261429/28981e7e-fb1e-49d4-a42b-6cac080c18de)

**Comment by dlemmermann** [comment]
Please give the label a max height ... do not let the header grow. We want the title to use "..." when too long.
