### ISSUE TITLE
Build new installer

### ISSUE THREAD

**Issue by dlemmermann** [dlemmermann/jfxcentral2#399]
Please create a new version of the installer for JFXCentral. Before doing so, make sure to delete .m2/repository/one and .m2/repository/com/sandec

**Comment by dlemmermann** [comment]
Attached an archive with icons for mac / windows.

[icons.zip](https://github.com/dlemmermann/jfxcentral2/files/12122416/icons.zip)

**Comment by mikehearn** [comment]
At what commit exactly? Can the icons be a part of the repository? It makes things easier if we can just point Conveyor at files inside the repository.

**Comment by dlemmermann** [comment]
I will add the icons. Once that is done I will create a tag for you to pull. ok?

**Comment by dlemmermann** [comment]
Branch: master
Version: 1.0.0-beta

You can now find all potential icons (I do not know which ones you need) in deployment/app-icons

**Comment by mikehearn** [comment]
@dlemmermann [Done](https://downloads.hydraulic.dev/jfxcentral2/download.html). It's sooooo slick I love it. Just a couple of notes:

1. The app doesn't shut down cleanly. It'd be a good idea to just have a System.exit call in there so leaked threads or other issues don't cause the app to hang around needing to be manually killed.
2. We switched to signing with the expensive EV certificate on Windows. You might need to uninstall the Windows version before installing the new release, if you get an install error. That's a one-off thing.
3. I enabled aggressive updates. It means a slightly slower startup, but, new versions of the code will be downloaded and applied immediately (on Mac and Windows). If you change the data formats such that old code wouldn't be able to read them, you'll need to let me know so we can push an update first before the new data format feature starts to be used.

💡 It'd be cool to accelerate or eliminate the initial update. One way would be to incorporate the data into the app itself, so the desktop update mechanisms update both code and data simultaneously and then the git checkout stuff can just be ignored for desktop. We have delta updates for Windows already and macOS delta updates are coming.

**Comment by dlemmermann** [comment]
Thank you for the compliments!

The link does not work ... "not found".

I like the idea of bundling the data for the desktop version! Let's look into that for version 2.

**Comment by dlemmermann** [comment]
To be more precise: the download links for Mac are not working.

**Comment by mikehearn** [comment]
That's weird. I just tried it and both archs work for me. What arch/browser are you on? If Chrome can you force it to hard refresh the page then try again? (shift+reload). I've noticed lately that Chrome has got quite reluctant to properly give up its caches sometimes, not sure why.

**Comment by dlemmermann** [comment]
I am on Intel Mac with Safari.

**Comment by dlemmermann** [comment]
Now it works. After pressing refresh.

**Comment by mikehearn** [comment]
I think the caching headers should be fixed now, sorry about that.

**Comment by dlemmermann** [comment]
Initial testing completed: please rebuild with version v1.0.0. Then we go live.

**Comment by mikehearn** [comment]
Done

**Comment by dlemmermann** [comment]
Thank you!
