### ISSUE TITLE
Purpose and operation of website unclear to newbies

### ISSUE THREAD

**Issue by mikehearn** [dlemmermann/jfxcentral2#412]
I showed jfxcentral and the app to a colleague. He made a few points:

The main "hero paragraph" doesn't explain what JavaFX is or what the purpose of the website is. Instead it tells you how to contribute, which is probably not the most important thing for new visitors to see.

Because jpro works so well, it's also not at all clear that the site is a JavaFX app. 

Maybe this paragraph would work better, with the "OpenJFX project ->" button replaced with "Contribute to this site":

"JavaFX is an advanced GUI toolkit accessible from any JVM language, which runs on desktop, mobile and the web. What you're looking at right now is a JavaFX app [run with jpro.one]!" (with the latter bit only visible on the web version)

Just a suggestion, it's not very important.

**Comment by dlemmermann** [comment]
This is excellent feedback, thank you! However, the "OpenJFX project" is not equivalent to contributing to this site. That project is the one used for developing JavaFX itself, not jfxcentral.

**Comment by mikehearn** [comment]
Yes I know but it's more likely that people will want to contribute to your project than OpenJFX given their rather glacial pace of merging PRs ;)
